class Failure {
  final String failureMessage;

  const Failure([this.failureMessage = "An unexpected Error Occurred"]);
}
